name: eaqoonsi
description: "A new eaqoonsi project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.3+1
  font_awesome_flutter: ^10.7.0
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  pin_code_fields: ^8.0.1
  flutter_animate: ^4.5.0
  go_router: ^14.0.1
  path_provider: ^2.1.3
  path: ^1.9.0
  camera: ^0.10.5+9 # camera: ^0.10.5+9
  flutter_image_compress: ^2.3.0  
  flutter_pdfview: ^1.3.2
  crypto: ^3.0.3
  encrypt: ^5.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  pretty_qr_code: ^3.3.0
  mobile_scanner: ^5.1.1
  jwt_decoder: ^2.0.1
  # flutter_face_api: ^6.2.3
  # flutter_face_core_basic: ^6.2.1

  # google_mlkit_face_detection: ^0.11.0
  # google_mlkit_selfie_segmentation: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true
  generate: true 
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
